import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Layout from '@/components/Layout';

function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={styles.main}>Content!</main>
      </Layout>
    </>
  );
}

export default Home;
