name: Build desktop app

on:
  push:
    branches:
      - main
  pull_request:
    branches: main
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-22.04
    name: test frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test:unit

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
